name: craft_policy
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACPolicyModel
  source: craft_policy
  use_args: false
  featurize_plan: false
  max_subtask_timesteps: 15
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints.policy.yaml"
  max_timesteps: 100
  max_policies: 4

#name: craft_transfer
#recipes: "resources/craft/recipes.yaml"
#world: 
#  name: CraftWorld
#model: 
#  name: ModularACModel
#  source: craft_holdout
#  use_args: false
#  max_subtask_timesteps: 15
#  baseline: state
#trainer: 
#  name: CurriculumTrainer
#  use_curriculum: true
#  improvement_threshold: 0.8
#  hints: "resources/craft/hints.holdout.yaml"
#  max_timesteps: 100
